version: "3.8"

services:
  nginx:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    container_name: t-nginx
    ports:
      - 80:80
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./app/server:/var/www/html
    networks:
      - app_network

  app:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    container_name: t-app
    volumes:
      - ./app/server:/var/www/html
    depends_on:
      - nginx
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
