version: "3.8"

volumes:
  db-store:

services:
  nginx:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    container_name: t-nginx
    ports:
      - 80:80
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./app/server:/var/www/src
    networks:
      - app_network

  app:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    container_name: t-app
    volumes:
      - ./app/server:/var/www/src
    depends_on:
      - nginx
      - db
    networks:
      - app_network

  db:
    build:
      context: .
      dockerfile: ./docker/db/Dockerfile
    container_name: t-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: database
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      TZ: "Asia/Tokyo"
    ports:
      - 3306:3306
    volumes:
      - db-store:/var/lib/mysql
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
